### ISSUE TITLE
What rpc server to use？

### ISSUE THREAD

**Issue by codinggg** [miguelmota/bitcoin-development-with-go#1]
This is a good project for me. And I want to run in my PC and use my owner bitcoin node, I find rpc command is not bitcoin native rpc command. For example, like `blockchain.address.listunspent` I am not found. 
So, What rpc server are you to use？how can I fix this problem. think you very much!!

**Comment by miguelmota** [comment]
Hi! You can try one of these RPC endpoints from the electrum wallet:

https://github.com/spesmilo/electrum/blob/master/electrum/servers.json

Some endpoints are hit or miss so give them all a try.
